# --- !Ups
CREATE TABLE "ROTAS" (
    "NAME" varchar(255) PRIMARY KEY, 
    "DESCRIPTION" varchar(255), 
    "ASSIGNED_USER_ID" int
);

CREATE TABLE "USERS" (
    "ID" SERIAL PRIMARY KEY, 
    "NAME" varchar(255) NOT NULL
);

CREATE TABLE "ROTA_USERS" (
    "ROTA_ID" int NOT NULL,
    "USER_ID" int NOT NULL,
    FOREIGN KEY ("ROTA_ID") REFERENCES "ROTAS"("ID") ON DELETE CASCADE, 
    FOREIGN KEY ("USER_ID") REFERENCES "USERS"("ID") ON DELETE CASCADE
);

# --- !Downs
DROP TABLE "ROTAS";
DROP TABLE "USERS";
DROP TABLE "ROTA_USERS";
