# --- !Ups
CREATE TABLE ROTAS (
    "ID" int SERIAL PRIMARY KEY, 
    "NAME" varchar NOT NULL, 
    "DESCRIPTION" varchar, 
    "ASSIGNED_USER_ID" int
);
INSERT INTO "ROTAS" VALUES (1, 'Daily Standup', 'Share updates and kick off the day', 8);
INSERT INTO "ROTAS" VALUES (2, 'Three Amigos', NULL, 7);
INSERT INTO "ROTAS" VALUES (3, 'Placeholder', NULL, NULL);

CREATE TABLE USERS (
    "ID" int SERIAL PRIMARY KEY, 
    "NAME" varchar NOT NULL
);
INSERT INTO "USERS" VALUES (1, 'Maria');
INSERT INTO "USERS" VALUES (2, 'John');
INSERT INTO "USERS" VALUES (3, 'Sophie');
INSERT INTO "USERS" VALUES (4, 'Liang');
INSERT INTO "USERS" VALUES (5, 'Mateo');
INSERT INTO "USERS" VALUES (6, 'David');
INSERT INTO "USERS" VALUES (7, 'Emily');
INSERT INTO "USERS" VALUES (8, 'Mohammad');

CREATE TABLE ROTA_USERS (
    "ROTA_ID" int NOT NULL,
    "USER_ID" int NOT NULL,
    FOREIGN KEY (ROTA_ID) REFERENCES ROTAS(ID), 
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
INSERT INTO "ROTA_USERS" VALUES (1, 1);
INSERT INTO "ROTA_USERS" VALUES (1, 2);
INSERT INTO "ROTA_USERS" VALUES (1, 3);
INSERT INTO "ROTA_USERS" VALUES (1, 4);
INSERT INTO "ROTA_USERS" VALUES (1, 5);
INSERT INTO "ROTA_USERS" VALUES (1, 6);
INSERT INTO "ROTA_USERS" VALUES (1, 7);
INSERT INTO "ROTA_USERS" VALUES (1, 8);
INSERT INTO "ROTA_USERS" VALUES (2, 4);
INSERT INTO "ROTA_USERS" VALUES (2, 7);
INSERT INTO "ROTA_USERS" VALUES (2, 8);

# --- !Downs
DROP TABLE "ROTAS";
DROP TABLE "USERS";
DROP TABLE "ROTA_USERS";