# fly.toml app configuration file generated for rota-api on 2024-03-31T09:10:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rota-api'
primary_region = 'lhr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[http_service]
internal_port = 9000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[services]]
http_checks = []
tcp_checks = []
protocol = 'tcp'
internal_port = 9000
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'connections'
hard_limit = 25
soft_limit = 20

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
