name: Deploy to staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_database_migrations:
    name: Deploy database migrations to Supabase
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: deploy-group
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      
      - name: Link supabase CLI to project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      
      - name: Push migrations
        run: supabase db push
  
  deploy_application:
    name: Deploy application to Fly.io
    needs: deploy_database_migrations
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency: deploy-group
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_CONFIG_FILE: fly.staging.toml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      
      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Build and test
        shell: bash
        run: sbt -v test
      
      - name: Build Docker image
        shell: bash
        run: sbt -v packageApplication
      
      - name: Deploy to Fly
        run: flyctl deploy --remote-only --config $FLY_CONFIG_FILE