name: Run tests on Pull Request

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and test
        shell: bash
        run: sbt -v test